jenkins Docker File Updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,74 +1,89 @@
-pipeline {
+// pipeline {
+//     agent any
+//     environment {
+//         IMAGE_NAME = "nileshdubey404/frontend"
+//         IMAGE_TAG  = "${BUILD_NUMBER}"
+//         APP_SERVER = "65.0.110.212"
+//     }
+//     stages {
+//         stage('Checkout') {
+//             steps {
+//                 git branch: 'main',
+//                 url: 'https://github.com/nileshdubey404/Jenkins_webapp.git'
+//             }
+//         }
+//         stage('Build Docker Image') {
+//             steps {
+//                 sh '''
+//                 docker build -f Docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+//                 '''
+//             }
+//         }
+//         stage('Docker Login') {
+//             steps {
+//                 withCredentials([
+//                     usernamePassword(
+//                         credentialsId: 'DockerCred',
+//                         usernameVariable: 'DOCKER_USER',
+//                         passwordVariable: 'DOCKER_PASS'
+//                     )
+//                 ]) {
+//                     sh '''
+//                     echo $DOCKER_PASS | docker login \
+//                     -u $DOCKER_USER \
+//                     --password-stdin
+//                     '''
+//                 }
+//             }
+//         }
+//         stage('Push Image') {
+//             steps {
+//                 sh '''
+//                 docker push $IMAGE_NAME:$IMAGE_TAG
+//                 docker tag \
+//                 $IMAGE_NAME:$IMAGE_TAG \
+//                 $IMAGE_NAME:latest
+//                 docker push $IMAGE_NAME:latest
+//                 '''
+//             }
+//         }
+//         stage('Deploy To App Server') {
+//             steps {
+//                 sh """
+//                 ssh ubuntu@$APP_SERVER '
+//                 docker pull $IMAGE_NAME:latest
+//                 docker stop frontend || true
+//                 docker rm frontend || true
+//                 docker run -d \
+//                 --name frontend \
+//                 -p 80:80 \
+//                 $IMAGE_NAME:latest
+//                 '
+//                 """
+//             }
+//         }
+//     }
+//     post {
+//         success {
+//             echo "Deployment Successful"
+//         }
+//         failure {
+//             echo "Deployment Failed"
+//         }
+//     }
+// }
+
+pipeline{
     agent any
-    environment {
-        IMAGE_NAME = "nileshdubey404/frontend"
-        IMAGE_TAG  = "${BUILD_NUMBER}"
-        APP_SERVER = "65.0.110.212"
-    }
-    stages {
-        stage('Checkout') {
-            steps {
-                git branch: 'main',
-                url: 'https://github.com/nileshdubey404/Jenkins_webapp.git'
-            }
-        }
-        stage('Build Docker Image') {
-            steps {
-                sh '''
-                docker build -f Docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+    stages{
+        stage('deployment'){
+            steps{
+                ssh ubuntu@ip '''
+                copy docker-compose.yaml /home/ubuntu/docker-compose.yaml
+                docker-compose -f /home/ubuntu/docker-compose.yaml down
+                docker-compose -f /home/ubuntu/docker-compose.yaml up -d
                 '''
             }
-        }
-        stage('Docker Login') {
-            steps {
-                withCredentials([
-                    usernamePassword(
-                        credentialsId: 'DockerCred',
-                        usernameVariable: 'DOCKER_USER',
-                        passwordVariable: 'DOCKER_PASS'
-                    )
-                ]) {
-                    sh '''
-                    echo $DOCKER_PASS | docker login \
-                    -u $DOCKER_USER \
-                    --password-stdin
-                    '''
-                }
-            }
-        }
-        stage('Push Image') {
-            steps {
-                sh '''
-                docker push $IMAGE_NAME:$IMAGE_TAG
-                docker tag \
-                $IMAGE_NAME:$IMAGE_TAG \
-                $IMAGE_NAME:latest
-                docker push $IMAGE_NAME:latest
-                '''
-            }
-        }
-        stage('Deploy To App Server') {
-            steps {
-                sh """
-                ssh ubuntu@$APP_SERVER '
-                docker pull $IMAGE_NAME:latest
-                docker stop frontend || true
-                docker rm frontend || true
-                docker run -d \
-                --name frontend \
-                -p 80:80 \
-                $IMAGE_NAME:latest
-                '
-                """
-            }
-        }
-    }
-    post {
-        success {
-            echo "Deployment Successful"
-        }
-        failure {
-            echo "Deployment Failed"
         }
     }
 }
